Traceback (most recent call last):
  File "/Users/knaaptime/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/basic.py", line 162, in execute
    executenb(
  File "/Users/knaaptime/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1077, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/knaaptime/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/knaaptime/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/knaaptime/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/knaaptime/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 526, in async_execute
    await self.async_execute_cell(
  File "/Users/knaaptime/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 822, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/knaaptime/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 730, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from geosnap import Community
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import sys, os
import warnings
warnings.filterwarnings("ignore")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-2e7643306583>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0mgeosnap[0m [0;32mimport[0m [0mCommunity[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mget_ipython[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mrun_line_magic[0m[0;34m([0m[0;34m'matplotlib'[0m[0;34m,[0m [0;34m'inline'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;32mimport[0m [0mseaborn[0m [0;32mas[0m [0msns[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;32mimport[0m [0msys[0m[0;34m,[0m [0mos[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Dropbox/projects/geosnap/geosnap/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     27[0m [0;31m# __version__ has to be define in the first line[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     28[0m [0;34m[0m[0m
[0;32m---> 29[0;31m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0manalyze[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     30[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mio[0m[0;34m[0m[0;34m[0m[0m
[1;32m     31[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mutil[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Dropbox/projects/geosnap/geosnap/analyze/__init__.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0;34m.[0m[0manalytics[0m [0;32mimport[0m [0mcluster[0m[0;34m,[0m [0mcluster_spatial[0m[0;34m,[0m [0mModelResults[0m[0;34m,[0m [0mpredict_labels[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mfrom[0m [0;34m.[0m[0mdynamics[0m [0;32mimport[0m [0msequence[0m[0;34m,[0m [0mtransition[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mfrom[0m [0;34m.[0m[0mincs[0m [0;32mimport[0m [0mlinc[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0m__all__[0m [0;34m=[0m [0;34m[[0m[0;34m'linc'[0m[0;34m,[0m [0;34m'sequence'[0m[0;34m,[0m [0;34m'transition'[0m[0;34m,[0m [0;34m'cluster'[0m[0;34m,[0m [0;34m'cluster_spatial'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Dropbox/projects/geosnap/geosnap/analyze/analytics.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;34m"""Tools for the spatial analysis of neighborhood change."""[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0;32mimport[0m [0mesda[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;32mimport[0m [0mgeopandas[0m [0;32mas[0m [0mgpd[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'esda'
ModuleNotFoundError: No module named 'esda'

